"""Primary keys to BIGINT

Revision ID: e0e7a6ef63d7
Revises: df8d9f423f2b
Create Date: 2017-06-01 16:26:09.965137

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e7a6ef63d7'
down_revision = 'df8d9f423f2b'
branch_labels = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_obm', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_obm', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
