"""added tpm metadata

Revision ID: bea78f4a7b08
Revises: 89630e3872ec
Create Date: 2016-11-07 16:37:36.069744

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea78f4a7b08'
down_revision = '89630e3872ec'
branch_labels = ('haas',)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TPM_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TPM_metadata')
    ### end Alembic commands ###
