#!/usr/bin/env python

# Copyright 2013-2014 Massachusetts Open Cloud Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied.  See the License for the specific language
# governing permissions and limitations under the License.

import sys
from haas import config
from haas.config import cfg
from subprocess import check_call

config.load()

driver_name = cfg.get('general', 'active_switch')
if driver_name != "dell":
    print("Not using dell switch.  Aborting.")
    sys.exit(1)

def create_bridge(vlan_no):
    vlan_no = str(vlan_no)
    trunk_nic = cfg.get('headnode', 'trunk_nic')
    bridge = 'br-vlan%s' % vlan_no
    vlan_nic = '%s.%s' % (trunk_nic, vlan_no)
    check_call(['brctl', 'addbr', bridge])
    check_call(['vconfig', 'add', trunk_nic, vlan_no])
    check_call(['brctl', 'addif', bridge, vlan_nic])
    check_call(['ifconfig', bridge, 'up', 'promisc'])
    check_call(['ifconfig', vlan_nic, 'up', 'promisc'])

r_list = cfg.get('switch dell', 'vlans').split(",")
for r in r_list:
    r = r.strip().split("-")
    if len(r) == 1:
        create_bridge(int(r[0]))
    else:
        for i in range(int(r[0]), int(r[1])+1):
            create_bridge(i)
