#!/usr/bin/env python

# Copyright 2013-2014 Massachusetts Open Cloud Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied.  See the License for the specific language
# governing permissions and limitations under the License.

from hil import config
from hil.config import cfg
from subprocess import call
from hil.ext.network_allocators.vlan_pool import get_vlan_list

config.load()

def create_bridge(vlan_no):
    vlan_no = str(vlan_no)
    trunk_nic = cfg.get('headnode', 'trunk_nic')
    bridge = 'br-vlan%s' % vlan_no
    vlan_nic = '%s.%s' % (trunk_nic, vlan_no)
    call(['brctl', 'addbr', bridge])
    call(['vconfig', 'add', trunk_nic, vlan_no])
    call(['brctl', 'addif', bridge, vlan_nic])
    call(['ifconfig', bridge, 'up', 'promisc'])
    call(['ifconfig', vlan_nic, 'up', 'promisc'])

for vlan in get_vlan_list():
    create_bridge(vlan)
