"""Primary keys to BIGINT

Revision ID: bcc65c173d83
Revises: b5b31d19257d
Create Date: 2017-06-01 16:35:35.072981

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc65c173d83'
down_revision = 'b5b31d19257d'
branch_labels = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_switch', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_switch', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER())
    # ### end Alembic commands ###
